name: winekeeper
publish_to: 'none'
description: WineKeeper MVP — учёт бутылок вина (Sprint 1)
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
